export const aiDocLink                      = "/assets/pdf/CHATBOT.pdf";
export const callAnalyticsDocLink           = "/assets/pdf/CallBack_Assist_Module_2018.pdf";
export const callBackDocLink                = "/assets/pdf/CallBack_Assist_Module_2018.pdf"; // Reusing assist module for callback
export const coBrowserDocLink               = "/assets/pdf/INAIPI_Click_to_Call.pdf"; // Closest match
export const crmDocLink                     = "/assets/pdf/Imperium_CRM_Connect.pdf";
export const dccDocLink                     = "/assets/pdf/ICEP.pdf"; // Closest match for contact center digital
export const qmsDocLink                     = "";
export const outBoundDocLink                = "";
export const smartRuleEngineDocLink         = "";
export const smartSurveyDocLink             = "/assets/pdf/CallBack_Assist_Module_2018.pdf";
export const smsDocLink                     = "/assets/pdf/INAIPI_Click_to_Call.pdf";
export const socialEngagementDocLink        = "/assets/pdf/Social-media.pdf";
export const ticketingDocLink               = "";
export const videoKycDocLink                = "";
export const socialMediaConnectorDocLink    = "/assets/pdf/Social-media.pdf";
