<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbfb2d5523cdd8d73efad9437c059ee70
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TBC\\IMK\\WEB\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TBC\\IMK\\WEB\\' => 
        array (
            0 => __DIR__ . '/..' . '/tbc/imk/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbfb2d5523cdd8d73efad9437c059ee70::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbfb2d5523cdd8d73efad9437c059ee70::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
