
@extends('layouts.app')
@section('meta')
{!!Helper::setMetaTags($meta)!!}
@stop
@section('content')
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Imperium Software Technologies FZCO",
  "image" : "https://www.imperiumapp.com/assets/image/products/customersurveymodule.jpg",
  "telephone" : "+9714 3202737",
  "email" : "support@imperiumapp.com",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "P.O. Box No : 342055, Dubai Silicon Oasis, Tech Hub 2 -240,",
    "addressCountry" : "Dubai, UAE"
  },
  "url" : "https://www.imperiumapp.com/products"
}
</script>
<!-- Inner Page Header serction start here -->
<div class="lite-breadcroumb-area innerbanner">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <h1>Products</h1>
            <div class="breadcroumb">
               <a href="{{ url('') }}">Home</a> &gt;
               <span class="current">Products</span>
            </div>
         </div>
      </div>
   </div>
</div>
<section id="about" class="service-area section-big section-padding greybg">
  <div class="container">
     <div class="topcontent">
       <div class="row">
          <div class="col-md-12 text-center">
             <div class="section-title">
                <h2>Our Products & Services</h2>
                <p>Choose our finest telecom software products to compliment your everyday business functionality</p>
             </div>
          </div>
       </div>
      <div class="row">
        <!-- <div class="col-md-4 col-sm-6 col-xs-12 match-height">
           <div class="service-box">
               <img src="{{ asset('image/products/contact-center.png') }}">
               <h3>Contact Center</h3>
               <p>Imperium offers a multi-channel contact center on Cloud that is smooth and scalable to meet the needs of a flourishing business. It is sustainable with skills such as call routing, call recording, call reporting, business integration and multichannel capabilities, all hosted on the most secure and legal cloud environment...
                   <p>
                       <a href="{{ url('products/contactcenter') }}">
                           More 
                           <i class="fa fa-arrow-right" aria-hidden="true"></i> 
                       </a>
                   </p>
               </p>
           </div>
           </div>
           <div class="col-md-4 col-sm-6 col-xs-12 match-height">
           <div class="service-box">
               <img src="{{ asset('image/products/contact-center.png') }}">
               <h3> Telephony</h3>
               <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus hendrerit semper quam, eget sollicitudin tortor sodales vel. Sed nec lacus eu eros convallis eleifend in eget ipsum. Sed nec consectetur risus, id luctus est. Vivamus eu euismod sapien. Curabitur fringilla ligula augue, eget semper mauris suscipit in...
                   <p>
                       <a href="{{ url('products/telephony') }}">
                           More 
                           <i class="fa fa-arrow-right" aria-hidden="true"></i> 
                       </a>
                   </p>
               </p>
           </div>
           </div>
           <div class="col-md-4 col-sm-6 col-xs-12 match-height">
           <div class="service-box">
               <img src="{{ asset('image/products/unified-communication.png') }}">
               <h3> Unified Communication </h3>
               <p>Work efficiently in a collaborative secure business environment. INAIPI offers unified communication as a tool for modern times. It establishes a 360°communication network for internal communication as well as customer relations over various platforms such as mobile phone, voicemail, e-mail, instant messaging tools...
                   <p>
                       <a href="{{ url('products/unifiedcommunication') }}">
                           More 
                           <i class="fa fa-arrow-right" aria-hidden="true"></i> 
                       </a>
                   </p>
               </p>
           </div>
           </div> -->      <div class="row d-flex flex-wrap" style="display: flex; flex-wrap: wrap;">
        <?php
            $productsFile = __DIR__ . '/../cms/data/products.json';
            $products = [];
            if (file_exists($productsFile)) {
                $products = json_decode(file_get_contents($productsFile), true);
            }
        ?>

        <?php if(!empty($products)): ?>
            <?php foreach($products as $product): ?>
                <div class="col-md-4 col-sm-6 col-xs-12 d-flex" style="display: flex; margin-bottom: 30px;">
                   <div class="service-box match-height w-100" style="display: flex; flex-direction: column; width: 100%;">
                    <a href="{{ url($product['link'] ?? '#') }}" style="flex-grow: 1; display: flex; flex-direction: column;">
                      <div class="thumb">
                         <div class="serviceimg">
                            <div class="image">
                                <?php
                                    $img = $product['image'] ?? 'image/products/default.jpg';
                                    $imgSrc = (strpos($img, 'http') === 0) ? $img : url($img);
                                ?>
                               <img src="{{ $imgSrc }}" style="width: 100%; height: 200px; object-fit: cover;">
                            </div>
                         </div>
                      </div>
                      <div class="servicecont" style="flex-grow: 1; display: flex; flex-direction: column;">
                         <h3 style="min-height: 50px;">{{ $product['title'] ?? 'Product Title' }}</h3>
                         <p class="match-height" style="flex-grow: 1;">
                             {{ Helper::limit_words($product['description'] ?? 'Product description...', 30) }}
                         </p>
                         <div style="margin-top: auto; padding-top: 10px;">
                             More 
                             <i class="fa fa-arrow-right" aria-hidden="true"></i> 
                         </div>
                      </div>
                    </a>
                   </div>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="col-md-12 text-center">
                <p>No products available at the moment.</p>
            </div>
        <?php endif; ?>
        </div>

        </div>
    </div>
  </div>
</section>
@endsection
