<?php
/**
 * Regenerates sitemap.xml from seo/pages.php.
 *
 * Run from the project root:   php tools/generate-sitemap.php
 *
 * Re-run this whenever a page is added, removed or renamed. The sitemap is a
 * static file (rather than a live route) so it costs nothing to serve and keeps
 * working even if PHP routing changes — the trade-off is that it must be
 * regenerated by hand, which is what this script is for.
 *
 * A URL belongs in the sitemap only if it returns 200 and is canonical to itself.
 * Anything added here must therefore also be in $allowed in libs/Bootstrap.php.
 */

$root = dirname(__DIR__);

$pages = require $root . '/seo/pages.php';
if (!is_array($pages) || !count($pages)) {
    fwrite(STDERR, "ERROR: seo/pages.php returned no pages.\n");
    exit(1);
}

// Must match SITE_URL in index.php, or Google sees the sitemap and the canonical
// tags pointing at two different hosts and trusts neither.
$base = 'https://www.imperiumapp.com';

// Cross-check against the router whitelist so a typo here cannot publish a 404
// into the sitemap — the single fastest way to lose crawl budget.
$bootstrap = file_get_contents($root . '/libs/Bootstrap.php');
$allowed   = [];
if (preg_match('/\$allowed\s*=\s*\[(.*?)\];/s', $bootstrap, $m)) {
    preg_match_all("/'([^']+)'/", $m[1], $slugMatches);
    $allowed = $slugMatches[1];
}

$lastmod = date('Y-m-d');
$entries = [];
$skipped = [];

foreach ($pages as $slug => $p) {
    if ($allowed && !in_array($slug, $allowed, true)) {
        $skipped[] = $slug;
        continue;
    }

    $loc = ($slug === 'index') ? $base . '/' : $base . '/' . $slug;

    $entries[] = sprintf(
        "  <url>\n    <loc>%s</loc>\n    <lastmod>%s</lastmod>\n    <changefreq>%s</changefreq>\n    <priority>%s</priority>\n  </url>",
        htmlspecialchars($loc, ENT_QUOTES, 'UTF-8'),
        $lastmod,
        isset($p['changefreq']) ? $p['changefreq'] : 'monthly',
        isset($p['priority']) ? $p['priority'] : '0.5'
    );
}

$xml  = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
$xml .= "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n";
$xml .= implode("\n", $entries) . "\n";
$xml .= "</urlset>\n";

file_put_contents($root . '/sitemap.xml', $xml);

echo "sitemap.xml written: " . count($entries) . " URLs (" . $base . ")\n";
if ($skipped) {
    echo "SKIPPED (not in Bootstrap \$allowed, would 404): " . implode(', ', $skipped) . "\n";
}
